FROM golangci/golangci-lint:v1.50

WORKDIR /usr/src/app

# Install system dependencies
RUN apt-get update && apt-get install -y gcc libgl1-mesa-dev xorg-dev

# Install Fyne CLI
RUN go install fyne.io/fyne/v2/cmd/fyne@latest